version: '3.7'

services:
  graphql-blog-api:
    container_name: graphql-blog-api
    build:
      context: .
      dockerfile: dev.Dockerfile
      args:
        - user_id=$UID
        - group_id=$GID
        - user=$USER
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - graphql-blog-db-dev
      - graphql-blog-db-test
    links:
      - graphql-blog-db-dev
      - graphql-blog-db-test
    working_dir: /app
    command: yarn start:debug

  graphql-blog-db-dev:
    container_name: graphql-blog-db-dev
    image: library/postgres:13.4-alpine
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: graphql-blog-db-dev
        target: /var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  graphql-blog-db-test:
    container_name: graphql-blog-db-test
    image: library/postgres:13.4-alpine
    ports:
      - "5433:5432"
    volumes:
      - type: volume
        source: graphql-blog-db-test
        target: /var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

volumes:
  graphql-blog-db-dev:
  graphql-blog-db-test:
